name: Base image build

on: 
  workflow_dispatch:
    branches: 
     - '*'
     - '!flatcap'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  
    - name: Build container image 
      run: docker build -f base.Dockerfile .
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        push: true
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/neomutt-base
        tag_with_sha: true
        tag_with_ref: true
