name: Base image build

on: 
  workflow_dispatch:
    branches: 
     - '*'
     - '!flatcap'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  
    # - name: Build container image 
    #   run: docker build -f base.Dockerfile .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner  }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Check location
      run: ls
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: base.Dockerfile
        platforms: linux/amd64
        push: true
        tags: nixmark/base-version:1.0.0

