name: C/C++ CI

on: 
  workflow_dispatch:
    branches: 
     - '*'
     - '!flatcap'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build docker 
      run: docker build -f build.Dockerfile .
