name: C/C++ CI

on: 
  workflow_dispatch:
    branches: 
     - '*'
     - '!flatcap'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  
    - name: Read file
      uses: juliangruber/read-file-action@v1.0.0
      id: package
      with:
        path: .github/workflows/packages.txt
    - name: Install packages 
      run: sudo apt install -y ${{ steps.package.outputs.content }}
