name: C/C++ CI

on: 
  workflow_dispatch:
    branches: 
     - '*'
     - '!flatcap'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  
    - name: Build docker 
      run: docker build -f build.Dockerfile .
