name: C/C++ CI

on: 
  workflow_dispatch:
    branches: 
     - '*'
     - '!flatcap'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  
#     - name: Read package list
#       uses: .github/workflows/
#       id: package
#       with:
#         path: packages.txt
    # - name: Install Dependencies
    #   run: apt install -y ${{ steps.package.outputs.content }}
    - name: list
      run: ls
