name: C/C++ CI

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Read package list
      uses: ./
      id: package
      with:
        path: packages.txt
    - name: Install Dependencies
      run: apt install -y ${{ steps.package.outputs.content }}
    - name: Checkout
      uses: actions/checkout@v2
